### ISSUE TITLE
bookmarks: have you handled a data source with no coordsys info?

### ISSUE THREAD

**Issue by tschwartzman** [sam-berg/ago-tools#6]
For bookmarks, I don't know if this is handled or not, but it occurred to me that things could go wrong if your datasource has no coordsys info.  The script asks for the geometries in 4326, but if there is no coordsys set on the data source (shapefile, feature class, etc), what does it do?

**Comment by sam-berg** [comment]
"presumed geographic" when in doubt.  good point- thanks.
